### ISSUE TITLE
Need More keybinding..like sublime eclipse keybindings

### ISSUE THREAD

**Issue by rijine** [enlangs/vscode-eclipse-keybindings#1]
https://gist.github.com/thbkrkr/3194275

**Comment by enlangs** [comment]
Thanks a lot .

**Comment by rijine** [comment]
@enlangs 

append this to your keybinding file

[
{
"key": "ctrl+shift+c",
"command": "editor.action.commentLine",
"when": "editorTextFocus"
},
{
"key": "ctrl+d",
"command": "editor.action.deleteLines",
"when": "editorTextFocus"
},
{
"key": "ctrl+k",
"command": "editor.action.addSelectionToNextFindMatch",
"when": "editorFocus"
},
{
"key": "alt+shift+2",
"command": "workbench.action.splitEditor"
},
{
"key": "ctrl+shift+f",
"command": "editor.action.format",
"when": "editorTextFocus"
},
]

**Comment by enlangs** [comment]
has been modified,thanks.
